project:
  type: website
  output-dir: docs

website:
  title: "Alister_DSPG24_Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Alister03USA
      - icon: linkedin
        href: https://www.linkedin.com/in/alister-gan-ee-shern-00831a230/
format:
  html:
    theme: cosmo
    css: styles.css



